import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#111317',
        'surface-bright': '#37393e',
        'on-primary-fixed': '#001a42',
        'primary-container': '#4d8eff',
        'secondary-fixed': '#6ffbbe',
        'on-background': '#e2e2e8',
        'surface-container-high': '#282a2e',
        'error-container': '#93000a',
        'surface-container-low': '#1a1c20',
        'on-surface': '#e2e2e8',
        'inverse-on-surface': '#2f3035',
        'inverse-primary': '#005ac2',
        'on-error': '#690005',
        'surface-container-lowest': '#0c0e12',
        'tertiary-fixed': '#ffdadb',
        'on-secondary': '#003824',
        'surface-variant': '#333539',
        'on-secondary-fixed': '#002113',
        'on-tertiary-container': '#5b0017',
        'surface-container': '#1e2024',
        background: '#111317',
        outline: '#8c909f',
        'on-secondary-container': '#00311f',
        'on-surface-variant': '#c2c6d6',
        'on-secondary-fixed-variant': '#005236',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-container': '#00285d',
        'on-tertiary-fixed-variant': '#92002a',
        'surface-tint': '#adc6ff',
        'inverse-surface': '#e2e2e8',
        'tertiary-fixed-dim': '#ffb2b7',
        surface: '#111317',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#333539',
        'tertiary-container': '#ff516a',
        primary: '#adc6ff',
        tertiary: '#ffb2b7',
        secondary: '#4edea3',
        'primary-fixed': '#d8e2ff',
        'on-tertiary': '#67001b',
        'on-tertiary-fixed': '#40000d',
        'on-primary': '#002e6a',
        'outline-variant': '#424754',
        'on-primary-fixed-variant': '#004395',
        'secondary-container': '#00a572',
        'primary-fixed-dim': '#adc6ff',
        error: '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '1rem',
        md: '1.5rem',
        xs: '0.5rem',
        unit: '8px',
        xl: '3rem',
        sm: '1rem',
        lg: '2rem',
        'container-max': '1200px',
      },
      fontFamily: {
        'body-lg': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'code-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
}

export default config
